sudo: required
serivces:
  - docker
before_install:
  - docker build -t wanwanzainaer/react-docker -f Dockerfile.dev .
script:
  - docker run wanwanzainaer/react-docker npm run test
dd:
  - openssl aes-256-cbc -K $encrypted_84182b89dffc_key -iv $encrypted_84182b89dffc_iv
    -in React-docker-09ec0d26a5b0.json.enc -out React-docker-09ec0d26a5b0.json -d

deploy:
  provider: gae
  keyfile: React-docker-09ec0d26a5b0.json
  project: react-docker-241301
  on:
    branch: master
